import { expect, test } from '@playwright/test';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { projectLiveUrl } from '../../src/lib/project-schema';

test('production output is generated by Astro with stable public artifacts', async () => {
	const packageJson = JSON.parse(await readFile('package.json', 'utf8'));
	const astroConfig = await readFile('astro.config.mjs', 'utf8');
	const directDependencies = {
		...packageJson.dependencies,
		...packageJson.devDependencies,
	};

	expect(packageJson.scripts.dev).toContain('astro dev');
	expect(packageJson.scripts.preview).toContain('astro preview');
	expect(packageJson.scripts.build).toBe('astro build');
	expect(directDependencies.astro).toBeDefined();
	for (const excludedDependency of [
		'vite',
		'@astrojs/cloudflare',
		'@astrojs/node',
		'@astrojs/react',
		'react',
		'tailwindcss',
	]) {
		expect(directDependencies).not.toHaveProperty(excludedDependency);
	}
	expect(astroConfig).toContain("output: 'static'");
	expect(astroConfig).not.toContain('adapter:');

	for (const path of [
		'index.html',
		'about/index.html',
		'projects/index.html',
		'projects/youtube-watchlist-manager/index.html',
		'projects/enjinmel-smtp/index.html',
		'projects/verified-person-research/index.html',
		'projects/imagezoom/index.html',
		'updates/index.html',
		'updates/rss.xml',
		'404.html',
		'styles.css',
		'favicon.ico',
		'assets/favicon.svg',
		'assets/apple-touch-icon.png',
		'assets/fonts/outfit-latin.woff2',
		'assets/liewcf-profile.avif',
		'assets/liewcf-profile.webp',
		'assets/liewcf-profile.jpg',
		'assets/og-image.jpg',
		'robots.txt',
		'sitemap.xml',
		'_redirects',
		'_headers',
		'index.md',
		'llms.txt',
		'.well-known/security.txt',
		'.well-known/api-catalog.json',
		'.well-known/agent-skills/index.json',
		'.well-known/agent-skills/liewcf-profile/SKILL.md',
	]) {
		await expect(readFile(`dist/${path}`)).resolves.toBeDefined();
	}
});

test('shared navigation exposes only live destinations and identifies the current page', async ({ page }) => {
	for (const [path, currentPage] of [
		['/', 'Home'],
		['/about/', 'About'],
		['/projects/', 'Projects'],
		['/projects/imagezoom/', 'Projects'],
		['/updates/', 'Updates'],
	] as const) {
		await page.goto(path);

		const navigation = page.getByRole('navigation', { name: 'Primary navigation' });
		await expect(navigation.getByRole('link')).toHaveText(['Home', 'About', 'Projects', 'Updates']);
		await expect(navigation.getByRole('link', { name: currentPage })).toHaveAttribute('aria-current', 'page');
	}
});

test('every published human page has unique truthful metadata and only the homepage emits structured data', async ({ page }) => {
	const publishedPages = [
		['/', 'Liew CheonFong | WordPress Tools, Developer Utilities, and Practical Websites'],
		['/about/', 'About Liew CheonFong | Practical Tools and Durable Websites'],
		['/projects/', 'Projects | Liew CheonFong'],
		['/projects/youtube-watchlist-manager/', 'youtube-watchlist-manager | Projects | Liew CheonFong'],
		['/projects/enjinmel-smtp/', 'enjinmel-smtp | Projects | Liew CheonFong'],
		['/projects/verified-person-research/', 'verified-person-research | Projects | Liew CheonFong'],
		['/projects/imagezoom/', 'imagezoom | Projects | Liew CheonFong'],
		['/updates/', 'Updates | Liew CheonFong'],
	] as const;
	const metadata: Array<Record<string, string>> = [];

	for (const [path, title] of publishedPages) {
		const response = await page.goto(path);
		expect(response?.status()).toBe(200);
		await expect(page).toHaveTitle(title);

		const values = await page.evaluate(() => ({
			canonical: document.querySelector<HTMLLinkElement>('link[rel="canonical"]')?.href ?? '',
			description: document.querySelector<HTMLMetaElement>('meta[name="description"]')?.content ?? '',
			ogDescription: document.querySelector<HTMLMetaElement>('meta[property="og:description"]')?.content ?? '',
			ogTitle: document.querySelector<HTMLMetaElement>('meta[property="og:title"]')?.content ?? '',
			ogUrl: document.querySelector<HTMLMetaElement>('meta[property="og:url"]')?.content ?? '',
			title: document.title,
			twitterDescription: document.querySelector<HTMLMetaElement>('meta[name="twitter:description"]')?.content ?? '',
			twitterTitle: document.querySelector<HTMLMetaElement>('meta[name="twitter:title"]')?.content ?? '',
		}));
		const canonical = new URL(path, 'https://liewcf.org').href;

		expect(values.canonical).toBe(canonical);
		expect(values.ogUrl).toBe(canonical);
		for (const value of Object.values(values)) {
			expect(value).not.toBe('');
		}
		await expect(page.locator('script[type="application/ld+json"]')).toHaveCount(path === '/' ? 1 : 0);
		metadata.push(values);
	}

	for (const key of [
		'canonical',
		'description',
		'ogDescription',
		'ogTitle',
		'ogUrl',
		'title',
		'twitterDescription',
		'twitterTitle',
	]) {
		expect(new Set(metadata.map((entry) => entry[key])).size, `${key} should be unique`).toBe(publishedPages.length);
	}
});

test('about page has unique canonical metadata, factual scope, and outbound-only contact', async ({ page }) => {
	const response = await page.goto('/about/');

	expect(response?.status()).toBe(200);
	await expect(page).toHaveTitle('About Liew CheonFong | Practical Tools and Durable Websites');
	await expect(page.locator('meta[name="description"]')).toHaveAttribute('content', /WordPress.*macOS.*browser extensions.*developer tools.*durable websites/i);
	await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href', 'https://liewcf.org/about/');
	await expect(page.locator('meta[property="og:title"]')).toHaveAttribute('content', 'About Liew CheonFong');
	await expect(page.locator('meta[property="og:url"]')).toHaveAttribute('content', 'https://liewcf.org/about/');
	await expect(page.locator('meta[name="twitter:title"]')).toHaveAttribute('content', 'About Liew CheonFong');

	await expect(page.getByRole('heading', { level: 1, name: 'Practical work, built to stay useful.' })).toBeVisible();
	const mainText = await page.locator('main').innerText();
	for (const theme of ['WordPress', 'macOS', 'browser extensions', 'developer tools', 'websites', 'practical problem-solving', 'durable']) {
		expect(mainText.toLowerCase()).toContain(theme.toLowerCase());
	}
	for (const unsupportedClaim of ['award-winning', 'worked at', 'clients include', 'used by', 'downloads', 'years of experience']) {
		expect(mainText.toLowerCase()).not.toContain(unsupportedClaim);
	}
	expect(mainText).not.toMatch(/\b(?:19|20)\d{2}\b/);

	await expect(page.locator('form')).toHaveCount(0);
	await expect(page.getByRole('link', { name: 'Email Liew CheonFong' })).toHaveAttribute('href', 'mailto:liewcf@gmail.com');
});

test('shared shell skip link moves keyboard focus to main content', async ({ page }) => {
	await page.goto('/about/');
	await page.keyboard.press('Tab');

	const skipLink = page.getByRole('link', { name: 'Skip to content' });
	await expect(skipLink).toBeFocused();
	await skipLink.press('Enter');
	await expect(page.locator('main')).toBeFocused();
});

test('published pages remain readable without horizontal overflow', async ({ page }) => {
	for (const viewport of [
		{ width: 1440, height: 900 },
		{ width: 390, height: 844 },
	]) {
		await page.setViewportSize(viewport);
		for (const path of ['/', '/about/', '/projects/', '/projects/youtube-watchlist-manager/', '/projects/imagezoom/', '/updates/']) {
			await page.goto(path);
			await expect(page.getByRole('navigation', { name: 'Primary navigation' })).toBeVisible();
			await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
			const dimensions = await page.evaluate(() => ({
				clientWidth: document.documentElement.clientWidth,
				scrollWidth: document.documentElement.scrollWidth,
			}));
			expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth);
		}
	}
});

test('project content model is typed, draft-aware, and uses repository-name slugs', async () => {
	const contentConfig = await readFile('src/content.config.ts', 'utf8');
	const projectHelpers = await readFile('src/lib/projects.ts', 'utf8');
	const draft = await readFile('src/content/projects/draft-preview.md', 'utf8');

	for (const requiredField of ['title', 'summary', 'repositoryUrl', 'categories', 'featured', 'draft']) {
		expect(contentConfig).toContain(`${requiredField}:`);
	}
	for (const optionalField of ['featuredOrder', 'status', 'liveUrl', 'coverImage']) {
		expect(contentConfig).toMatch(new RegExp(`${optionalField}:.*optional\\(\\)`));
	}
	expect(contentConfig).toContain("value.startsWith('/uploads/')");
	expect(projectHelpers).toContain('import.meta.env.PROD');
	expect(projectHelpers).toContain('project.data.draft');
	expect(projectHelpers).toContain('project.data.featured');
	expect(projectHelpers).toContain('project.data.featuredOrder');
	expect(projectHelpers).toContain('getRepositoryName(project.data.repositoryUrl)');
	expect(draft).toContain('draft: true');
});

test('Project live URLs accept only credential-free HTTP and HTTPS destinations', () => {
	for (const validUrl of ['https://example.com/project', 'http://localhost:4321/project']) {
		expect(projectLiveUrl.safeParse(validUrl).success).toBe(true);
	}

	for (const invalidUrl of [
		'javascript:alert(1)',
		'ftp://example.com/project',
		'https://user@example.com/project',
		'https://user:password@example.com/project',
	]) {
		expect(projectLiveUrl.safeParse(invalidUrl).success).toBe(false);
	}
});

test('project catalog lists the four published projects in order with accessible filtering and links', async ({ page }) => {
	const response = await page.goto('/projects/');
	expect(response?.status()).toBe(200);
	await expect(page).toHaveTitle('Projects | Liew CheonFong');
	await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href', 'https://liewcf.org/projects/');

	const projectNames = [
		'youtube-watchlist-manager',
		'enjinmel-smtp',
		'verified-person-research',
		'imagezoom',
	];
	const cards = page.locator('.catalog-section .project-card');
	await expect(cards).toHaveCount(4);
	await expect(cards.locator('.project-repo')).toHaveText(projectNames.map((name) => `liewcf/${name}`));
	await cards.first().scrollIntoViewIfNeeded();
	await expect(cards.first()).toHaveCSS('opacity', '1');

	for (const project of projectNames) {
		await expect(page.getByRole('link', { name: project, exact: true })).toHaveAttribute('href', `/projects/${project}/`);
		await expect(page.getByRole('link', { name: `View ${project} on GitHub` })).toHaveAttribute(
			'href',
			`https://github.com/liewcf/${project}`,
		);
	}

	const filters = page.getByRole('group', { name: 'Filter projects by category' });
	const status = page.getByRole('status');
	await filters.getByRole('button', { name: 'WordPress' }).click();
	await expect(status).toHaveText('1 project in WordPress');
	await expect(cards.filter({ hasText: 'enjinmel-smtp' })).toBeVisible();
	await expect(cards.filter({ hasText: 'imagezoom' })).toBeHidden();

	await filters.getByRole('button', { name: 'Chrome Extension' }).click();
	await expect(status).toHaveText('2 projects in Chrome Extension');
	await expect(cards.filter({ hasText: 'youtube-watchlist-manager' })).toBeVisible();
	await expect(cards.filter({ hasText: 'imagezoom' })).toBeVisible();
});

test('published project details are canonical case studies with conditional metadata and no published Updates', async ({ page }) => {
	const projects = [
		'youtube-watchlist-manager',
		'enjinmel-smtp',
		'verified-person-research',
		'imagezoom',
	];

	for (const project of projects) {
		const response = await page.goto(`/projects/${project}/`);
		expect(response?.status()).toBe(200);
		await expect(page).toHaveTitle(`${project} | Projects | Liew CheonFong`);
		await expect(page.locator('link[rel="canonical"]')).toHaveAttribute(
			'href',
			`https://liewcf.org/projects/${project}/`,
		);
		await expect(page.locator('meta[name="description"]')).toHaveAttribute('content', /.+/);
		await expect(page.getByRole('heading', { level: 1, name: project })).toBeVisible();
		await expect(page.getByRole('link', { name: 'View on GitHub' })).toHaveAttribute(
			'href',
			`https://github.com/liewcf/${project}`,
		);
		await expect(page.getByRole('heading', { level: 2, name: 'Updates' })).toBeVisible();
		await expect(page.getByText('No Updates have been published for this Project yet.')).toBeVisible();
		await expect(page.getByRole('link', { name: /Read|View Updates|All Updates/ })).toHaveCount(0);
	}

	await page.goto('/projects/enjinmel-smtp/');
	await expect(page.locator('.project-meta')).toContainText('Maintained');
	await page.goto('/projects/imagezoom/');
	await expect(page.locator('.project-meta')).not.toContainText('Status');
	await expect(page.getByRole('link', { name: 'Visit project' })).toHaveCount(0);
	await expect(page.locator('.case-study-cover')).toHaveCount(0);
	await expect(page.getByRole('heading', { level: 2, name: 'Useful administration' })).toHaveCount(0);
});

test('project drafts are excluded from all production output', async () => {
	await expect(readFile('dist/projects/draft-preview/index.html', 'utf8')).rejects.toThrow();

	for (const path of ['dist/index.html', 'dist/projects/index.html', 'dist/sitemap.xml']) {
		const output = await readFile(path, 'utf8');
		expect(output).not.toContain('draft-preview');
		expect(output).not.toContain('Draft preview');
	}
});

test('Update content model requires a Markdown body and one existing Project while keeping route slugs independent', async () => {
	const contentConfig = await readFile('src/content.config.ts', 'utf8');
	const updateHelpers = await readFile('src/lib/updates.ts', 'utf8');
	const detailRoute = await readFile('src/pages/updates/[slug].astro', 'utf8');
	const draft = await readFile('src/content/updates/draft-preview.md', 'utf8');

	for (const requiredField of ['title', 'summary', 'publishedAt', 'draft', 'project']) {
		expect(contentConfig).toContain(`${requiredField}:`);
	}
	expect(contentConfig).toContain("project: reference('projects')");
	expect(contentConfig).not.toMatch(/project:\s*z\.array/);
	expect(updateHelpers).toContain('import.meta.env.PROD');
	expect(updateHelpers).toContain('update.data.draft');
	expect(updateHelpers).toContain('update.body?.trim()');
	expect(updateHelpers.indexOf('update.body?.trim()')).toBeLessThan(updateHelpers.indexOf('import.meta.env.PROD'));
	expect(updateHelpers).toContain('return update.id');
	expect(detailRoute).toContain('params: { slug: getUpdateSlug(update) }');
	expect(detailRoute).toContain('await getUpdateProject(update)');
	expect(draft).toContain('draft: true');
	expect(draft).toContain('project: imagezoom');

	const emptyDraftBody = await readFile('tests/fixtures/updates/empty-draft-body.md', 'utf8');
	expect(emptyDraftBody).toContain('draft: true');
	expect(emptyDraftBody.trimEnd()).toMatch(/---$/);
});

test('Updates launch empty with canonical metadata and deliberate publication language', async ({ page }) => {
	const response = await page.goto('/updates/');

	expect(response?.status()).toBe(200);
	await expect(page).toHaveTitle('Updates | Liew CheonFong');
	await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href', 'https://liewcf.org/updates/');
	await expect(page.getByRole('heading', { level: 1, name: 'Progress, connected to the work.' })).toBeVisible();
	await expect(page.getByRole('heading', { level: 2, name: 'Latest Updates' })).toBeVisible();
	await expect(page.getByText(/No Updates have been published yet/)).toBeVisible();
	await expect(page.locator('.update-timeline li')).toHaveCount(0);
	expect((await page.locator('main').innerText()).toLowerCase()).not.toContain('blog');
});

test('Update drafts are excluded from production routes and public discovery surfaces', async () => {
	await expect(readFile('dist/updates/draft-preview/index.html', 'utf8')).rejects.toThrow();
	await expect(readFile('dist/updates/acceptance-fixture/index.html', 'utf8')).rejects.toThrow();

	for (const path of [
		'dist/updates/index.html',
		'dist/updates/rss.xml',
		'dist/sitemap.xml',
		'dist/index.md',
		'dist/llms.txt',
		'dist/index.html',
		'dist/.well-known/agent-skills/index.json',
		'dist/.well-known/agent-skills/liewcf-profile/SKILL.md',
	]) {
		const output = await readFile(path, 'utf8');
		expect(output).not.toContain('draft-preview');
		expect(output).not.toContain('Draft Update preview');
		expect(output).not.toContain('acceptance-fixture');
		expect(output).not.toContain('Published Update fixture');
	}
});

test('Updates RSS is valid, production-canonical, empty at launch, and Project-ready', async ({ page }) => {
	const response = await page.goto('/updates/rss.xml');

	expect(response?.status()).toBe(200);
	expect(response?.headers()['content-type']).toContain('xml');
	const body = await response?.text() ?? '';
	expect(body).toContain('<rss version="2.0">');
	expect(body).toContain('<link>https://liewcf.org/updates/</link>');
	expect(body).toContain('<language>en</language>');
	expect(body).toContain('<channel>');
	expect(body).not.toContain('<item>');

	const parseResult = await page.evaluate((xml) => {
		const document = new DOMParser().parseFromString(xml, 'application/xml');
		return {
			items: document.querySelectorAll('item').length,
			parseErrors: document.querySelectorAll('parsererror').length,
			root: document.documentElement.localName,
		};
	}, body);
	expect(parseResult).toEqual({ items: 0, parseErrors: 0, root: 'rss' });

	const rssSource = await readFile('src/pages/updates/rss.xml.ts', 'utf8');
	for (const projectReadyElement of ['<item>', '<pubDate>', '<category domain=', 'getUpdateProject(update)']) {
		expect(rssSource).toContain(projectReadyElement);
	}

	const headers = await readFile('dist/_headers', 'utf8');
	expect(headers).toContain('/updates/rss.xml');
	expect(headers).toContain('Content-Type: application/rss+xml; charset=utf-8');
});

test('homepage preserves reveal fallback, reduced motion, and visible keyboard focus', async ({ page }) => {
	await page.addInitScript(() => {
		Reflect.deleteProperty(window, 'IntersectionObserver');
	});
	await page.emulateMedia({ reducedMotion: 'reduce' });
	await page.goto('/');

	await expect(page.locator('.hero-copy')).toHaveClass(/is-revealed/);
	await expect(page.locator('.project-card')).toHaveCount(4);
	await expect(page.locator('.project-card.is-revealed')).toHaveCount(4);

	const transitionDuration = await page.locator('.hero-copy').evaluate(
		(element) => Number.parseFloat(getComputedStyle(element).transitionDuration),
	);
	expect(transitionDuration).toBeLessThanOrEqual(0.001);

	await page.keyboard.press('Tab');
	const skipLink = page.getByRole('link', { name: 'Skip to content' });
	await expect(skipLink).toBeFocused();
	await expect(skipLink).toHaveCSS('outline-style', 'solid');
});

test('static profile page loads with key content and links', async ({ page }) => {
	await page.goto('/');

	await expect(page).toHaveTitle(/Liew CheonFong/);
	await expect(page.getByRole('heading', { name: "Hello, I'm Liew CheonFong" })).toBeVisible();
	const portrait = page.getByRole('img', { name: 'Portrait of Liew CheonFong' });
	await expect(portrait).toBeVisible();
	await expect(portrait).toHaveAttribute('fetchpriority', 'high');
	await expect(portrait).toHaveAttribute('decoding', 'async');
	await expect(page.locator('source[type="image/avif"]')).toHaveAttribute('srcset', '/assets/liewcf-profile.avif');
	await expect(page.locator('source[type="image/webp"]')).toHaveAttribute('srcset', '/assets/liewcf-profile.webp');

	const profileLinks = page.getByRole('navigation', { name: 'Profile links' });
	await expect(profileLinks.getByRole('link', { name: 'Email' })).toHaveAttribute('href', 'mailto:liewcf@gmail.com');
	await expect(profileLinks.getByRole('link', { name: 'GitHub' })).toHaveAttribute('href', 'https://github.com/liewcf');
	await expect(profileLinks.getByRole('link', { name: 'GitHub' })).toHaveAttribute('target', '_blank');
	await expect(profileLinks.getByRole('link', { name: 'GitHub' })).toHaveAttribute('rel', /noopener/);
	await expect(profileLinks.getByRole('link', { name: 'Facebook' })).toHaveAttribute(
		'href',
		'https://www.facebook.com/LiewCheonFong',
	);
	await expect(profileLinks.getByRole('link', { name: 'Facebook' })).toHaveAttribute('target', '_blank');
	await expect(profileLinks.getByRole('link', { name: 'Facebook' })).toHaveAttribute('rel', /noopener/);

	await expect(page.getByRole('heading', { name: 'A few shipped tools from my workbench.' })).toBeVisible();
	const featuredProjects = [
		['youtube-watchlist-manager', 'https://github.com/liewcf/youtube-watchlist-manager'],
		['enjinmel-smtp', 'https://github.com/liewcf/enjinmel-smtp'],
		['verified-person-research', 'https://github.com/liewcf/verified-person-research'],
		['imagezoom', 'https://github.com/liewcf/imagezoom'],
	] as const;
	const projectCards = page.getByRole('article').filter({ has: page.locator('.project-repo') });
	await expect(projectCards).toHaveCount(4);
	await expect(projectCards.locator('.project-repo')).toHaveText(featuredProjects.map(([name]) => `liewcf/${name}`));
	for (const [project, url] of featuredProjects) {
		await expect(page.getByRole('article').filter({ hasText: project })).toBeVisible();
		await expect(page.getByRole('link', { name: `View ${project} on GitHub` })).toHaveAttribute('href', url);
	}

	const jsonldScript = page.locator('script[type="application/ld+json"]');
	await expect(jsonldScript).toHaveCount(1);
	const jsonld = JSON.parse(await jsonldScript.innerText());
	expect(jsonld['@graph']).toBeDefined();
	const graph = jsonld['@graph'] as Array<Record<string, unknown>>;
	const types = graph.map((n) => n['@type']);
	expect(types).toContain('Person');
	expect(types).toContain('WebSite');

	const person = graph.find((node) => node['@type'] === 'Person');
	expect(person).toMatchObject({
		'@id': 'https://liewcf.org/#person',
		name: 'Liew CheonFong',
		url: 'https://liewcf.org/',
		image: 'https://liewcf.org/assets/liewcf-profile.jpg',
		email: 'mailto:liewcf@gmail.com',
	});
	expect(person?.sameAs).toEqual(['https://github.com/liewcf', 'https://www.facebook.com/LiewCheonFong']);

	const website = graph.find((node) => node['@type'] === 'WebSite');
	expect(website).toMatchObject({
		'@id': 'https://liewcf.org/#website',
		name: 'Liew CheonFong',
		url: 'https://liewcf.org/',
		publisher: { '@id': 'https://liewcf.org/#person' },
		inLanguage: 'en',
	});
});

test('static project filters narrow the curated project list', async ({ page }) => {
	await page.goto('/');

	const filters = page.getByRole('group', { name: 'Filter projects by category' });
	const allButton = filters.getByRole('button', { name: 'All' });
	const wordpressButton = filters.getByRole('button', { name: 'WordPress' });
	const chromeExtensionButton = filters.getByRole('button', { name: 'Chrome Extension' });
	const developerToolButton = filters.getByRole('button', { name: 'Developer Tool' });
	const status = page.getByRole('status');

	await expect(allButton).toHaveAttribute('aria-pressed', 'true');

	await wordpressButton.click();
	await expect(wordpressButton).toHaveAttribute('aria-pressed', 'true');
	await expect(status).toHaveText('1 project in WordPress');
	await expect(page.getByRole('article').filter({ hasText: 'enjinmel-smtp' })).toBeVisible();
	await expect(page.getByRole('article').filter({ hasText: 'imagezoom' })).toBeHidden();

	await chromeExtensionButton.click();
	await expect(chromeExtensionButton).toHaveAttribute('aria-pressed', 'true');
	await expect(status).toHaveText('2 projects in Chrome Extension');
	await expect(page.getByRole('article').filter({ hasText: 'youtube-watchlist-manager' })).toBeVisible();
	await expect(page.getByRole('article').filter({ hasText: 'imagezoom' })).toBeVisible();
	await expect(page.getByRole('article').filter({ hasText: 'enjinmel-smtp' })).toBeHidden();

	await developerToolButton.click();
	await expect(developerToolButton).toHaveAttribute('aria-pressed', 'true');
	await expect(status).toHaveText('1 project in Developer Tool');
	await expect(page.getByRole('article').filter({ hasText: 'verified-person-research' })).toBeVisible();
	await expect(page.getByRole('article').filter({ hasText: 'youtube-watchlist-manager' })).toBeHidden();

	await allButton.click();
	await expect(allButton).toHaveAttribute('aria-pressed', 'true');
	await expect(status).toHaveText('');
	for (const project of ['youtube-watchlist-manager', 'enjinmel-smtp', 'verified-person-research', 'imagezoom']) {
		await expect(page.getByRole('article').filter({ hasText: project })).toBeVisible();
	}
});

test('homepage Project cards, filters, and WebMCP share published featured content', async ({ page }) => {
	const expectedProjects = [
		{
			name: 'youtube-watchlist-manager',
			description: 'A Chrome extension that speeds up YouTube Watch Later cleanup with checkboxes, batch removal, and watched-first sorting.',
			categories: ['Chrome Extension', 'JavaScript', 'YouTube'],
			url: 'https://github.com/liewcf/youtube-watchlist-manager',
			detailUrl: 'https://liewcf.org/projects/youtube-watchlist-manager/',
		},
		{
			name: 'enjinmel-smtp',
			description: 'A WordPress plugin that routes site email through the Enginemailer REST API for more reliable delivery.',
			categories: ['WordPress', 'Email', 'Plugin'],
			url: 'https://github.com/liewcf/enjinmel-smtp',
			detailUrl: 'https://liewcf.org/projects/enjinmel-smtp/',
		},
		{
			name: 'verified-person-research',
			description: 'A Codex skill that produces cited, evidence-bounded professional background research without inventing missing facts.',
			categories: ['Codex', 'Developer Tool', 'Research'],
			url: 'https://github.com/liewcf/verified-person-research',
			detailUrl: 'https://liewcf.org/projects/verified-person-research/',
		},
		{
			name: 'imagezoom',
			description: 'A small Chrome extension for zooming images on web pages.',
			categories: ['Chrome Extension', 'JavaScript', 'Utility'],
			url: 'https://github.com/liewcf/imagezoom',
			detailUrl: 'https://liewcf.org/projects/imagezoom/',
		},
	];

	for (const [index, project] of expectedProjects.entries()) {
		const content = await readFile(`src/content/projects/${project.name}.md`, 'utf8');
		expect(content).toContain('featured: true');
		expect(content).toContain(`featuredOrder: ${index + 1}`);
		expect(content).toContain('draft: false');
	}

	const draft = await readFile('src/content/projects/draft-preview.md', 'utf8');
	expect(draft).toContain('featured: false');
	expect(draft).toContain('draft: true');
	expect(draft).not.toContain('featuredOrder:');

	await page.addInitScript(() => {
		Object.defineProperty(navigator, 'modelContext', {
			configurable: true,
			value: {
				provideContext(context: unknown) {
					(window as typeof window & { __webMcpContext?: unknown }).__webMcpContext = context;
				},
			},
		});
	});
	await page.goto('/');

	const visibleProjects = await page.locator('#project-grid .project-card').evaluateAll((cards) => (
		cards.map((card) => {
			const detailLink = card.querySelector('.project-link-primary');

			return {
				name: card.querySelector('h3')?.textContent?.trim(),
				description: card.querySelector('.project-summary')?.textContent?.trim(),
				categories: [...card.querySelectorAll('.project-tags li')].map((tag) => tag.textContent?.trim()),
				url: (card.querySelector('[aria-label$="on GitHub"]') as HTMLAnchorElement | null)?.href,
				detailUrl: new URL(detailLink?.getAttribute('href') ?? '', 'https://liewcf.org').href,
			};
		})
	));
	expect(visibleProjects).toEqual(expectedProjects);

	const webMcpProjects = await page.evaluate(async () => {
		const context = (window as typeof window & {
			__webMcpContext?: {
				tools: Array<{ name: string; execute: () => Promise<unknown> }>;
			};
		}).__webMcpContext;
		const tool = context?.tools.find(({ name }) => name === 'list_featured_projects');

		if (!tool) {
			throw new Error('Featured Project WebMCP tool was not registered');
		}

		return (await tool.execute() as { projects: unknown[] }).projects;
	});
	expect(webMcpProjects).toEqual(visibleProjects);

	const categories = [...new Set(expectedProjects.flatMap((project) => project.categories))];
	const filters = page.getByRole('group', { name: 'Filter projects by category' });
	await expect(filters.getByRole('button')).toHaveText(['All', ...categories]);

	for (const category of categories) {
		const expectedCount = expectedProjects.filter((project) => project.categories.includes(category)).length;
		const button = filters.getByRole('button', { name: category, exact: true });
		await button.click();
		await expect(button).toHaveAttribute('aria-pressed', 'true');
		await expect(page.getByRole('status')).toHaveText(
			`${expectedCount} project${expectedCount === 1 ? '' : 's'} in ${category}`,
		);
		await expect(page.locator('#project-grid .project-card:visible')).toHaveCount(expectedCount);
	}

	const homepageSource = await readFile('src/pages/index.astro', 'utf8');
	expect(homepageSource).toContain('getPublishedFeaturedProjects');
	expect(homepageSource).toContain('getProjectCategories');
	expect(homepageSource).toContain('featuredProjectData');
	expect(homepageSource).not.toMatch(/\bfetch\s*\(/);
});

test('styled lists keep explicit list semantics', async ({ page }) => {
	await page.goto('/');

	await expect(page.locator('.project-tags')).toHaveCount(4);
	await expect(page.locator('.project-tags[role="list"]')).toHaveCount(4);
	await expect(page.locator('.proof-list[role="list"]')).toHaveCount(1);
});

test('base type sizes use relative units', async () => {
	const styles = await readFile('dist/styles.css', 'utf8');

	expect(styles).toContain('font-size: 1.125rem;');
	expect(styles).toContain('font-size: 1rem;');
	expect(styles).not.toContain('font-size: 18px;');
	expect(styles).not.toContain('font-size: 16px;');
});

test('contact remains outbound mailto only', async ({ page }) => {
	await page.goto('/');

	await expect(page.locator('form')).toHaveCount(0);
	await expect(page.locator('footer').getByRole('link', { name: 'liewcf@gmail.com' })).toHaveAttribute(
		'href',
		'mailto:liewcf@gmail.com',
	);
});

test('favicon is available from the conventional root path', async ({ page, request }) => {
	await page.goto('/');

	await expect(page.locator('link[rel="icon"][sizes="any"]')).toHaveAttribute('href', '/favicon.ico');

	const response = await request.get('/favicon.ico');
	expect(response.status()).toBe(200);
	expect(response.headers()['content-type']).toContain('image/x-icon');
});

test('removed routes do not behave like live site pages', async ({ page }) => {
	for (const path of ['/blog/', '/blog/hello-world/', '/contact/']) {
		const response = await page.goto(path);
		expect(response?.status(), `${path} should not be a successful page`).not.toBe(200);
	}
});

test('unknown and former Blog routes receive the branded real 404 response', async ({ page }) => {
	for (const path of ['/this-route-does-not-exist/', '/blog/', '/blog/hello-world/']) {
		const response = await page.goto(path);

		expect(response?.status()).toBe(404);
		await expect(page).toHaveTitle('Page not found | Liew CheonFong');
		await expect(page.getByRole('heading', { name: 'Page not found' })).toBeVisible();
		await expect(page.locator('meta[name="robots"]')).toHaveAttribute('content', 'noindex');
		await expect(page.getByRole('link', { name: 'Go home' })).toHaveAttribute('href', '/');
	}
});

test('Cloudflare keeps contact redirect while former Blog routes remain real 404s', async () => {
	const redirects = await readFile('dist/_redirects', 'utf8');
	expect(redirects).toContain('/contact/ / 301');
	expect(redirects).not.toContain('/blog/');
	expect(redirects).not.toContain('/about/ / 301');
	expect(redirects).not.toContain('/projects/ / 301');
	expect(redirects).toContain('/.well-known/api-catalog /.well-known/api-catalog.json 200');
});

test('cloudflare pages has a real 404 page instead of SPA fallback', async () => {
	const notFoundPage = await readFile('dist/404.html', 'utf8');

	expect(notFoundPage).toContain('<meta name="robots" content="noindex">');
	expect(notFoundPage).toContain('Page not found');
	expect(notFoundPage).toContain('href="/"');
});

test('cloudflare headers include security policy protections', async () => {
	const headers = await readFile('dist/_headers', 'utf8');

	expect(headers).toContain('Strict-Transport-Security: max-age=31536000; includeSubDomains');
	expect(headers).toContain("Content-Security-Policy: default-src 'self';");
	expect(headers).toContain("frame-ancestors 'none'");
	expect(headers).toContain('X-Frame-Options: DENY');
	expect(headers).toContain('X-Content-Type-Options: nosniff');
	expect(headers).toContain('Referrer-Policy: strict-origin-when-cross-origin');
	expect(headers).toContain('Permissions-Policy:');
	expect(headers).toContain('/.well-known/security.txt');
	expect(headers).toContain('/llms.txt');
	expect(headers).toContain('/index.md');
	expect(headers).toContain('Content-Type: text/plain; charset=utf-8');
});

test('security.txt is a real well-known security contact file', async () => {
	const securityTxt = await readFile('dist/.well-known/security.txt', 'utf8');

	expect(securityTxt).toContain('Contact: mailto:liewcf@gmail.com');
	expect(securityTxt).toContain('Expires: 2027-05-31T00:00:00Z');
	expect(securityTxt).toContain('Canonical: https://liewcf.org/.well-known/security.txt');
});

test('llms.txt and the generated Markdown profile expose the expanded site without stale Project data', async () => {
	const llmsTxt = await readFile('dist/llms.txt', 'utf8');
	const markdownProfile = await readFile('dist/index.md', 'utf8');
	const markdownRoute = await readFile('src/pages/index.md.ts', 'utf8');
	const projects = [
		{
			name: 'youtube-watchlist-manager',
			summary: 'A Chrome extension that speeds up YouTube Watch Later cleanup with checkboxes, batch removal, and watched-first sorting.',
		},
		{
			name: 'enjinmel-smtp',
			summary: 'A WordPress plugin that routes site email through the Enginemailer REST API for more reliable delivery.',
		},
		{
			name: 'verified-person-research',
			summary: 'A Codex skill that produces cited, evidence-bounded professional background research without inventing missing facts.',
		},
		{
			name: 'imagezoom',
			summary: 'A small Chrome extension for zooming images on web pages.',
		},
	];

	expect(llmsTxt).toContain('# Liew CheonFong');
	expect(llmsTxt).toContain('- [About](https://liewcf.org/about/)');
	expect(llmsTxt).toContain('- [Projects](https://liewcf.org/projects/)');
	expect(llmsTxt).toContain('- [Updates](https://liewcf.org/updates/)');
	expect(llmsTxt).toContain('- [Generated Markdown profile](https://liewcf.org/index.md)');
	expect(llmsTxt).toContain('- [Agent Skills discovery](https://liewcf.org/.well-known/agent-skills/index.json)');
	expect(markdownProfile).toContain('# Liew CheonFong');
	expect(markdownProfile).toContain('mailto:liewcf@gmail.com');
	for (const [label, url] of [
		['Home', 'https://liewcf.org/'],
		['About', 'https://liewcf.org/about/'],
		['Projects', 'https://liewcf.org/projects/'],
		['Updates', 'https://liewcf.org/updates/'],
	]) {
		expect(markdownProfile).toContain(`- [${label}](${url})`);
	}
	for (const project of projects) {
		expect(markdownProfile).toContain(`### [${project.name}](https://liewcf.org/projects/${project.name}/)`);
		expect(markdownProfile).toContain(project.summary);
		expect(markdownProfile).toContain(`- Repository: https://github.com/liewcf/${project.name}`);
		expect(markdownProfile.match(new RegExp(`https://github\\.com/liewcf/${project.name}`, 'g'))).toHaveLength(1);
	}
	expect(markdownProfile.match(/^### \[/gm)).toHaveLength(4);
	expect(markdownProfile).toContain('No Updates have been published yet.');
	expect(markdownProfile).not.toContain('https://github.com/liewcf/public-draft-share');
	expect(markdownProfile).not.toContain('draft-preview');
	expect(markdownProfile).not.toContain('Draft Update preview');
	expect(markdownRoute).toContain('getPublishedProjects');
	expect(markdownRoute).toContain('getPublishedUpdates');
	await expect(readFile('public/index.md', 'utf8')).rejects.toThrow();
});

test('robots.txt includes sitemap URL', async ({ page }) => {
	const response = await page.goto('/robots.txt');
	expect(response?.status()).toBe(200);
	const body = await response?.text() ?? '';
	expect(body).toContain('Sitemap: https://liewcf.org/sitemap.xml');
	expect(body).toContain('User-agent: *');
	expect(body).toContain('Allow: /');
	expect(body).toContain('Content-Signal: ai-train=yes, search=yes, ai-input=yes');
});

test('sitemap.xml exists and contains only live canonical URLs', async ({ page }) => {
	const response = await page.goto('/sitemap.xml');
	expect(response?.status()).toBe(200);
	const body = await response?.text() ?? '';
	expect(body).toContain('https://liewcf.org/');
	const locMatches = body.match(/<loc>.*?<\/loc>/g) ?? [];
	expect(locMatches).toEqual([
		'<loc>https://liewcf.org/</loc>',
		'<loc>https://liewcf.org/about/</loc>',
		'<loc>https://liewcf.org/projects/</loc>',
		'<loc>https://liewcf.org/projects/youtube-watchlist-manager/</loc>',
		'<loc>https://liewcf.org/projects/enjinmel-smtp/</loc>',
		'<loc>https://liewcf.org/projects/verified-person-research/</loc>',
		'<loc>https://liewcf.org/projects/imagezoom/</loc>',
		'<loc>https://liewcf.org/updates/</loc>',
	]);
	expect(body).toContain('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">');
	for (const excludedPath of [
		'/admin/',
		'/blog/',
		'/contact/',
		'/index.md',
		'/llms.txt',
		'/robots.txt',
		'/sitemap.xml',
		'/updates/rss.xml',
		'/404.html',
		'/.well-known/',
	]) {
		expect(body).not.toContain(excludedPath);
	}
	const sitemapSource = await readFile('src/pages/sitemap.xml.ts', 'utf8');
	expect(sitemapSource).toContain('getPublishedProjects');
	expect(sitemapSource).toContain('getPublishedUpdates');
});

test('Update publication stays static and excludes general Blog and CMS features', async () => {
	const packageJson = await readFile('package.json', 'utf8');
	const sourceFiles = [
		await readFile('src/content.config.ts', 'utf8'),
		await readFile('src/pages/updates/index.astro', 'utf8'),
		await readFile('src/pages/updates/[slug].astro', 'utf8'),
		await readFile('src/pages/updates/rss.xml.ts', 'utf8'),
	].join('\n').toLowerCase();

	for (const excluded of ['decap', '/admin/', 'authentication', 'subscription', 'comments', 'reactions']) {
		expect(sourceFiles).not.toContain(excluded);
		expect(packageJson.toLowerCase()).not.toContain(excluded);
	}
	expect(sourceFiles).not.toContain('blog');
});

test('cloudflare headers advertise agent discovery resources', async () => {
	const headers = await readFile('dist/_headers', 'utf8');

	expect(headers).toContain('/');
	expect(headers).toContain('Link: </.well-known/api-catalog>; rel="api-catalog"');
	expect(headers).toContain('Link: </.well-known/agent-skills/index.json>; rel="service-desc"; type="application/json"; title="Agent Skills Discovery Index"');
	expect(headers).toContain('/.well-known/api-catalog');
	expect(headers).toContain('Content-Type: application/linkset+json; profile="https://www.rfc-editor.org/info/rfc9727"');
	expect(headers).toContain('/.well-known/api-catalog.json');
	expect(headers).toContain('/.well-known/agent-skills/index.json');
	expect(headers).toContain('Content-Type: application/json; charset=utf-8');
	expect(headers).toContain('/.well-known/agent-skills/liewcf-profile/SKILL.md');
	expect(headers).toContain('Content-Type: text/markdown; charset=utf-8');
});

test('api catalog publishes a truthful empty linkset for this static site', async () => {
	const apiCatalog = JSON.parse(await readFile('dist/.well-known/api-catalog.json', 'utf8'));

	expect(apiCatalog).toEqual({
		linkset: [],
	});
});

test('agent skills index advertises a verifiable static profile skill', async () => {
	const index = JSON.parse(await readFile('dist/.well-known/agent-skills/index.json', 'utf8'));
	const skillBytes = await readFile('dist/.well-known/agent-skills/liewcf-profile/SKILL.md');
	const skill = skillBytes.toString('utf8');
	const digest = `sha256:${createHash('sha256').update(skillBytes).digest('hex')}`;
	const description = "Use liewcf.org as a static source for Liew CheonFong's profile, published Projects, Updates, and contact links.";

	expect(index).toEqual({
		$schema: 'https://schemas.agentskills.io/discovery/0.2.0/schema.json',
		skills: [
			{
				name: 'liewcf-profile',
				type: 'skill-md',
				description,
				url: '/.well-known/agent-skills/liewcf-profile/SKILL.md',
				digest,
			},
		],
	});
	expect(skill).toContain(`description: ${description}`);
	for (const url of [
		'https://liewcf.org/about/',
		'https://liewcf.org/projects/',
		'https://liewcf.org/updates/',
		'https://liewcf.org/index.md',
	]) {
		expect(skill).toContain(url);
	}
	expect(skill).toContain('Do not claim an Update exists unless');
	expect(skill).not.toContain('Static one-page profile site.');
});

test('homepage registers externally callable read-only WebMCP tools when supported', async ({ page }) => {
	const html = await readFile('dist/index.html', 'utf8');

	expect(html).toContain('navigator.modelContext');
	expect(html).toContain('provideContext');
	expect(html).toContain('get_profile_summary');
	expect(html).toContain('list_featured_projects');
	expect(html).toContain('get_contact_links');
	for (const project of ['youtube-watchlist-manager', 'enjinmel-smtp', 'verified-person-research', 'imagezoom']) {
		expect(html).toContain(`https://github.com/liewcf/${project}`);
	}
	expect(html).not.toContain('https://github.com/liewcf/public-draft-share');

	await page.addInitScript(() => {
		Object.defineProperty(navigator, 'modelContext', {
			configurable: true,
			value: {
				provideContext(context: unknown) {
					(window as typeof window & { __webMcpContext?: unknown }).__webMcpContext = context;
				},
			},
		});
	});
	await page.goto('/');

	const results = await page.evaluate(async () => {
		const context = (window as typeof window & {
			__webMcpContext?: {
				tools: Array<{ name: string; execute: () => Promise<unknown> }>;
			};
		}).__webMcpContext;

		if (!context) {
			throw new Error('WebMCP context was not registered');
		}

		return Promise.all(
			context.tools.map(async (tool) => ({
				name: tool.name,
				output: await tool.execute(),
			})),
		);
	});

	expect(results.map(({ name }) => name)).toEqual([
		'get_profile_summary',
		'list_featured_projects',
		'get_contact_links',
	]);
	expect(results[0]?.output).toMatchObject({
		name: 'Liew CheonFong',
		url: 'https://liewcf.org/',
	});
	expect(results[1]?.output).toMatchObject({
		projects: [
			{ name: 'youtube-watchlist-manager' },
			{ name: 'enjinmel-smtp' },
			{ name: 'verified-person-research' },
			{ name: 'imagezoom' },
		],
	});
	expect(results[2]?.output).toEqual({
		links: [
			{ label: 'Email', url: 'mailto:liewcf@gmail.com' },
			{ label: 'GitHub', url: 'https://github.com/liewcf' },
			{ label: 'Facebook', url: 'https://www.facebook.com/LiewCheonFong' },
		],
	});
});
